// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixsqqmqipnekmkfgicvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4c3FxbXFpcG5la21rZmdpY3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzOTkwMDIsImV4cCI6MjA3NDk3NTAwMn0.CgtFxX3_LiES3XZxD5ey6bBmTQQ0TyTmu6e7gRKR80M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});