name: Lighthouse CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Build site
        run: pnpm build

      - name: Run Lighthouse CI (static dist)
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: ./lighthouserc.json
          temporaryPublicStorage: true
          uploadArtifacts: true
          runs: 1
          # The action will auto-serve ./dist because staticDistDir is defined in lighthouserc.json
